#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
source "$BASE/lib/common.sh"
# shellcheck source=/dev/null
source "$BASE/lib/toml.sh"
# shellcheck source=/dev/null
source "$BASE/lib/sdk.sh"
# shellcheck source=/dev/null
source "$BASE/lib/maven.sh"

PROJECT="${1:-}"
[ -z "$PROJECT" ] && die "project path missing"

BUILD="$PROJECT/build"
OBJ="$BUILD/obj"
GENERATED="$BUILD/generated"
DEPS_JARS="$BUILD/deps/jars"

mkdir -p "$OBJ"

TARGET_SDK="$(toml_get "$PROJECT/Candy.toml" target_sdk 34)"
ANDROID_JAR="$(resolve_android_jar "$TARGET_SDK")" \
    || die "android.jar not found for API $TARGET_SDK. Set ANDROID_HOME or see docs/SDK.md"

# Dependency jars resolved by deps.sh (empty if the project declares none).
DEPS_CP=""
if [ -d "$DEPS_JARS" ]; then
    while IFS= read -r -d '' j; do
        DEPS_CP="${DEPS_CP:+$DEPS_CP:}$j"
    done < <(find "$DEPS_JARS" -name "*.jar" -print0)
fi
CLASSPATH="$ANDROID_JAR${DEPS_CP:+:$DEPS_CP}"

log_info "Finding Kotlin files..."

# Arrays + -print0 instead of an unquoted $(find ...) — a path or file
# name containing a space used to silently split into two arguments and
# break the whole kotlinc invocation.
KOTLIN_FILES=()
while IFS= read -r -d '' f; do
    KOTLIN_FILES+=("$f")
done < <(find "$PROJECT/src" -name "*.kt" -print0)

# Java sources: both hand-written project .java (if any) and the R.java
# generated by aapt2 link in resources.sh.
JAVA_FILES=()
while IFS= read -r -d '' f; do
    JAVA_FILES+=("$f")
done < <(find "$PROJECT/src" "$GENERATED" -name "*.java" -print0 2>/dev/null || true)

[ "${#KOTLIN_FILES[@]}" -eq 0 ] && [ "${#JAVA_FILES[@]}" -eq 0 ] \
    && die "No Kotlin or Java files found in $PROJECT/src"

# --- Kotlin step (skipped entirely for pure-Java projects) ---
if [ "${#KOTLIN_FILES[@]}" -gt 0 ]; then
    require_cmd kotlinc

    KOTLINC_ARGS=()

    UI="$(toml_get "$PROJECT/Candy.toml" ui views)"
    if [ "$UI" = "compose" ]; then
        log_info "Compose project — resolving matching compiler plugin..."
        KOTLIN_VERSION="$(kotlinc -version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n1)"
        [ -z "$KOTLIN_VERSION" ] && die "Could not detect kotlinc version (needed to fetch a matching Compose compiler plugin)"
        case "$KOTLIN_VERSION" in
            1.*) die "Jetpack Compose here requires Kotlin 2.0+ (K2 compose compiler). Installed: kotlinc $KOTLIN_VERSION" ;;
        esac

        PLUGIN_JAR="$(maven_fetch org.jetbrains.kotlin kotlin-compose-compiler-plugin-embeddable "$KOTLIN_VERSION" jar)" \
            || die "Could not fetch Compose compiler plugin for Kotlin $KOTLIN_VERSION (check network, or pin a different kotlin package version)"

        KOTLINC_ARGS+=(-Xplugin="$PLUGIN_JAR")
        log_info "Compose compiler plugin: $PLUGIN_JAR"
    fi

    log_info "Compiling ${#KOTLIN_FILES[@]} Kotlin file(s)..."

    # kotlinc is given the .java files too, but ONLY so Kotlin code can
    # resolve symbols against them (e.g. R.layout.activity_main). kotlinc
    # never emits .class files for Java sources — that is javac's job. If we
    # stopped here, R.class (and R$layout, R$drawable, ...) would never
    # exist, dex.sh would silently dex an incomplete class set, and any code
    # that touches R would crash at runtime with NoClassDefFoundError even
    # though this step reported success.
    kotlinc \
        "${KOTLINC_ARGS[@]}" \
        "${KOTLIN_FILES[@]}" \
        "${JAVA_FILES[@]}" \
        -classpath "$CLASSPATH" \
        -d "$OBJ"
else
    log_info "No Kotlin files — pure Java project"
fi

# --- Java step (always runs if there are .java files: project sources
# and/or generated R.java). Needs $OBJ on its classpath so it can see
# whatever kotlinc already produced, for mixed Kotlin+Java projects. ---
if [ "${#JAVA_FILES[@]}" -gt 0 ]; then
    require_cmd javac
    log_info "Compiling ${#JAVA_FILES[@]} Java file(s) (incl. R.java)..."
    javac \
        -classpath "$CLASSPATH:$OBJ" \
        -d "$OBJ" \
        "${JAVA_FILES[@]}"
fi

echo
log_ok "Kotlin/Java OK"
